version: '3'

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - <port_vmess>:8080
      - <port_naive>:8090
      - <port_hy2>:10080/udp
    volumes:
      - ./data:/data
      - <cert_path>:<cert_path>
      - <cert_private_key_path>:<cert_private_key_path>
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    entrypoint: ["/bin/bash", "/data/entry.sh"]